commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki, name = "entry"),
    path("search/", views.search, name = "search"),
    path("createpage/", views.createPage, name = "createpage"),
    path("editpage/<str:title>", views.editPage, name = "editpage"),
    path("random/", views.randomPage, name = "randompage"),
    path("error/<str:message>", views.error, name = "error")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import random
import markdown2

from . import util

class NewSearchForm(forms.Form):
    search = forms.CharField(label = "Search")

class CreatePageForm(forms.Form):
    title = forms.CharField(label = "Title:")
    content = forms.CharField(label = "Content:", widget=forms.Textarea)

class EditPageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewSearchForm
    })

def error(request, message):
    return render(request, "encyclopedia/error.html", {
        "message": message,
        "form": NewSearchForm
    })

def wiki(request, title):
    if util.get_entry(title) is None:
        return redirect("encyclopedia:error", message = "404: Page not found!")
    result = markdown2.markdown(util.get_entry(title))
    return render(request, "encyclopedia/page.html", {
        "entries": result,
        "title": title,
        "form": NewSearchForm
    })

def search(request):
    if request.method == "POST":
        form = NewSearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            if util.get_entry(search) is None:
                search_result = util.list_entries_advanced(search)
                return render(request, "encyclopedia/searchresult.html", {
                            "title": search,
                            "search": search_result,
                            "form": NewSearchForm
                            })
            return redirect("encyclopedia:entry", title = search)
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewSearchForm
    })

def createPage(request):
    if request.method == "POST":
        form = CreatePageForm(request.POST)
        if form.is_valid():
            class Submit:
                title = form.cleaned_data["title"]
                content = form.cleaned_data["content"]
            if util.get_entry(Submit.title) is not None:
                return render(request, "encyclopedia/createpage.html", {
                            "form": NewSearchForm,
                            "createPageForm": CreatePageForm,
                            "message": "Page already exist!"
                 })
            else:
                util.save_entry(Submit.title, Submit.content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title': Submit.title})) 
    return render(request, "encyclopedia/createpage.html", {
        "form": NewSearchForm,
        "createPageForm": CreatePageForm
    })

def editPage(request, title):
    content = util.get_entry(title)
    if request.method == "POST":
        form = EditPageForm(request.POST)
        if form.is_valid():
            new_content = form.cleaned_data["content"]
            util.save_entry(title, new_content)
        return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title': title})) 
    EditPageForm.initial = content
    return render(request, "encyclopedia/editpage.html", {
        "form": NewSearchForm,
        "editPageForm": EditPageForm(initial={'content': content}),
        "title": title
    })

def randomPage(request):
    array = util.list_entries()
    print(array)
    id = random.randint(0,int(len(array))-1)
    return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title': array[id]}))

encyclopedia/templates/encyclopedia/createpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Creation
{% endblock %}

{% block body %}
    <h1>Page creation</h1>
    <h3>Title:</h3>
    <h5>{{ message }}</h5>
    <form action="{% url 'encyclopedia:createpage' %}" method="post">
        {% csrf_token %}
        {{ createPageForm.title }}
       
    
    <div>
        <h3>Content:</h3>
        {% csrf_token %}
        {{ createPageForm.content }}
    </div>
    <input type="Submit">
</form>
    

{% endblock %}

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Edition
{% endblock %}

{% block body %}
    <h1>Page Edition</h1>
    <h3>Title: {{ title }}</h3>
    <form action="{% url 'encyclopedia:editpage' title=title%}" method="post">
    <div>
        <h3>Content:</h3>
        {% csrf_token %}
        {{ editPageForm }}
    </div>
    <input type="Submit">
</form>
    

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki
{% endblock %}

{% block body %}
    <h1>Eror: {{ message }}</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li>
            <a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a>
        </li>
        {% empty %}
        <li> No data! </li>
        {% endfor %}

    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:createpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ entries|safe }}
    <div>
        <a href="{% url 'encyclopedia:editpage' title=title %}">Edit this page</a>
    </div>
        
    
{% endblock %}

encyclopedia/templates/encyclopedia/searchresult.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
   
<h2>Looking for: {{ title }} </h2>
<h3>Results:</h3>
<ul>
    {% for result in search %}
    <li>
        <a href="{% url 'encyclopedia:entry' title=result %}">{{ result }}</a>
    </li>
    {% empty %}
    <li> No data! </li>
    {% endfor %}

</ul>

{% endblock %}